export const copy = {
  nav: {
    features: "Features",
    privacy: "Privacy",
    models: "Models",
    github: "GitHub",
    download: "Download for macOS",
  },
  hero: {
    eyebrow: "Local voice-to-text for macOS · No cloud",
    title: "Your voice,",
    titleAccent: "everywhere you type.",
    sub: "Hold one shortcut. Speak naturally. Your words appear wherever you are typing — transcribed locally on your Mac. Audio never leaves your machine.",
    ctaPrimary: "Download for macOS",
    ctaSecondary: "View on GitHub",
    ctaNote: "macOS 14+ · Apple Silicon · 43 MB to start",
    demoCaption: "Press and hold, speak, release — text appears at your cursor.",
  },
  trust: ["Local", "Private", "Fast", "Your model", "Every text field"],
  problem: {
    title: "Typing is slow.\nSpeaking is natural.",
    p1: "You type all day. Messages, code, notes, docs. Supertype bridges the gap — you speak, your Mac types.",
    p2: "One shortcut. Every app.",
  },
  how: {
    title: "Four steps. Zero new habits.",
    steps: [
      { n: "01", h: "Press", p: "Hold your shortcut. The overlay appears — you’re live." },
      { n: "02", h: "Speak", p: "Talk naturally. Pauses are fine. VAD keeps up." },
      { n: "03", h: "Release", p: "Let go. Local model turns speech into formatted text." },
      { n: "04", h: "Keep typing", p: "Text appears where you were. No paste, no window switch." },
    ],
  },
  models: {
    eyebrow: "Local models",
    title: "Choose the model.\nKeep it on your Mac.",
    sub: "Download once. Use offline. Switch anytime in Settings → Speech. All models run on-device via Metal.",
    cards: [
      {
        id: "parakeet",
        name: "Parakeet TDT 0.6B",
        badge: "Recommended",
        meta: "600 MB · FP16 · 16 GB+ · CC‑BY‑4.0",
        desc: "Fast streaming, strong accuracy. Best when you have headroom.",
        accent: false,
      },
      {
        id: "base",
        name: "Whisper Base",
        badge: null,
        meta: "142 MB · Q5_0 · 8 GB+ · MIT",
        desc: "Balanced for everyday dictation without thinking about RAM.",
        accent: false,
      },
      {
        id: "tiny",
        name: "Whisper Tiny",
        badge: "Default",
        meta: "75 MB · Q5_0 · Lightest · MIT",
        desc: "Try in seconds. Upgrade later without changing how you dictate.",
        accent: false,
      },
      {
        id: "tiny-q4",
        name: "Whisper Tiny Q4",
        badge: "Ultra light",
        meta: "43 MB · Q4_0 · <8 GB · MIT",
        desc: "Smallest download. Ideal for testing on any Mac.",
        accent: false,
      },
    ],
    foot: "Sizes, licenses and attribution shown in the app. No cloud API. Switch without re-recording.",
  },
  privacy: {
    eyebrow: "Privacy",
    title: "Your voice\nstays on your Mac.",
    sub: "Architecture, not policy. Audio is passed from microphone to memory, through VAD and a local model, formatted, inserted where you type, then discarded.",
    bullets: [
      "No audio upload for transcription",
      "No transcript upload by default",
      "Offline after one model download",
      "History is text-only, opt-in, pruned automatically",
      "Zero audio tables — verified by migration tests",
    ],
    diagram: ["Microphone", "Local VAD + ASR", "Formatter + Dictionary", "Your app"],
  },
  workflow: {
    eyebrow: "Where you work",
    title: "It works where\nyou already work.",
    sub: "Cursor, VS Code, Slack, Notes, Safari, Chrome — native text fields, Electron apps and browsers. If you can type there, you can speak there.",
  },
  performance: {
    eyebrow: "Performance",
    title: "Fast by design,\nnot by claim.",
    sub: "The pipeline is engineered for immediacy, not demos. Real measurements from the local benchmark suite — no fabricated numbers.",
    principles: ["Lightweight quantized models", "Streaming partials every second", "Native macOS audio + Metal", "Bounded buffers, off-lock transcribe"],
  },
  final: {
    title: "Stop typing\neverything.",
    sub: "Download once. Hold one key. Speak — and keep working.",
    cta: "Download for macOS",
    note: "Free for local use · No account · Source on GitHub",
  },
  footer: {
    tagline: "Local voice-to-text for macOS. Private, fast, offline.",
    links: [
      { label: "Privacy", href: "#privacy" },
      { label: "Models", href: "#models" },
      { label: "GitHub", href: "https://github.com/poswalsameer/supertype" },
      { label: "Releases", href: "https://github.com/poswalsameer/supertype/releases" },
    ],
  },
} as const;
